{{- if .Values.backend.dummy-secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: voice-backend-secrets
  namespace: {{ include "frida-carclaims.namespace" . }}
  labels:
    app: voice-backend
    {{- include "frida-carclaims.labels" . | nindent 4 }}
type: Opaque
stringData:
  CHAT_API_KEY: 'sk-...'
  TRANSCRIPTION_API_KEY: 'sk-...'
{{- end }}