global:
  namespace: frida-carclaims-stage
  partOf: frida-carclaims
  environment: stage

frontend:
  image:
    repository: quay.io/mklaasse/frida-carclaims-frontend
    tag: latest

backend:
  serviceName: frida-carclaims-stage
  image:
    repository: quay.io/mklaasse/frida-carclaims-backend-ai
    tag: latest
  config:
    litellmBaseUrl: "https://litellm-litemaas.apps.prod.rhoai.rh-aiservices-bu.com/v1/"
    chatModel: "Qwen3.6-35B-A3B"
    # OpenAI-compatible transcription
    transcriptionBaseUrl: "https://api.openai.com/v1/"
    transcriptionModel: "whisper-1"

