global:
  namespace: frida-carclaims-stage
  partOf: frida-carclaims
  environment: stage

frontend:
  image:
    repository: quay.io/mklaasse/frida-carclaims-frontend
    tag: latest

backend:
  serviceName: frida-carclaims-stage
  image:
    repository: quay.io/mklaasse/frida-carclaims-backend-ai
    tag: latest
  config:
    litellmBaseUrl: "https://maas-rhdp.apps.maas.redhatworkshops.io/v1/"
    chatModel: "deepseek-r1-distill-qwen-14b"
    litellmTimeout: "120s"
    transcriptionBaseUrl: "https://maas-rhdp.apps.maas.redhatworkshops.io/v1"
    transcriptionModel: "66a6383b-bbd8-44fa-b128-7c2902263ead"
    logLevelClickKlaassen: "INFO"
    logLevelLangchain4j: "INFO"
    httpAccessLogEnabled: "true"

