{{- if .Values.whisper.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-model
  namespace: {{ include "frida-carclaims.namespace" . }}
  labels:
    app: whisper
    {{- include "frida-carclaims.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.whisper.pvcSize }}
{{- end }}
