{{- if .Values.whisper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: {{ include "frida-carclaims.namespace" . }}
  labels:
    app: whisper
    {{- include "frida-carclaims.labels" . | nindent 4 }}
spec:
  selector:
    app: whisper
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
{{- end }}
