global:
  namespace: frida-carclaims-prod
  partOf: frida-carclaims
  environment: prod

frontend:
  replicas: 2
  image:
    repository: quay.io/mklaasse/frida-carclaims-frontend
    tag: latest

backend:
  replicas: 2
  serviceName: frida-carclaims-prod
  image:
    repository: quay.io/mklaasse/frida-carclaims-backend-ai
    tag: latest
  config:
    litellmBaseUrl: "https://maas-rhdp.apps.maas.redhatworkshops.io/v1/"
    chatModel: "deepseek-r1-distill-qwen-14b"
    litellmTimeout: "120s"
    transcriptionBaseUrl: "https://maas-rhdp.apps.maas.redhatworkshops.io/v1"
    transcriptionModel: "whisper-small"
    logLevelClickKlaassen: "WARN"
    logLevelLangchain4j: "WARN"
    httpAccessLogEnabled: "true"

