global:
  namespace: frida-car-claims-prod
  partOf: frida-carclaims
  environment: prod
  skipNamespace: true

frontend:
  replicas: 2
  image:
    repository: quay.io/mklaasse/frida-carclaims-frontend
    tag: latest

backend:
  replicas: 2
  serviceName: frida-carclaims-prod
  image:
    repository: quay.io/mklaasse/frida-carclaims-backend-ai
    tag: latest
  config:
    chatBaseUrl: "https://api.openai.com/v1/"
    chatModel: "gpt-4o-mini"
    chatTimeout: "120s"
    transcriptionBaseUrl: "https://api.openai.com/v1/"
    transcriptionModel: "whisper-1"
    logLevelClickKlaassen: "WARN"
    logLevelLangchain4j: "WARN"
    httpAccessLogEnabled: "true"

