apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frida-carclaims-dev
  labels:
    app.kubernetes.io/part-of: frida-carclaims
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sa-mw-dach/frida-carclaims-ai-gitops.git
    targetRevision: main
    path: charts/frida-carclaims
    helm:
      valueFiles:
        - ../../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: frida-car-claims-dev
  ignoreDifferences:
    - group: route.openshift.io
      kind: Route
      jsonPointers:
        - /spec/host
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
