apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frida-carclaims-dev
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: frida-carclaims
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sa-mw-dach/frida-carclaims-ai-gitops.git
    targetRevision: main
    path: charts/frida-carclaims
    helm:
      valueFiles:
        - ../../environments/dev/values.yaml
      parameters:
        - name: global.appsDomain
          value: apps.cluster-f4wcp.f4wcp.sandbox2418.opentlc.com
  destination:
    server: https://kubernetes.default.svc
    namespace: frida-carclaims-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
