#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/environments/cluster.yaml"
ENV_FILE="${REPO_ROOT}/.env"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

CLUSTER_APPS_DOMAIN="${CLUSTER_APPS_DOMAIN:-}"

if [[ -z "$CLUSTER_APPS_DOMAIN" ]]; then
  echo "ERROR: CLUSTER_APPS_DOMAIN is not set."
  echo ""
  echo "Set the OpenShift apps domain for your cluster, for example:"
  echo "  export CLUSTER_APPS_DOMAIN=apps.mycluster.example.com"
  echo ""
  echo "Discover it on an OpenShift cluster with:"
  echo "  oc get ingresscontroller default -n openshift-ingress-operator -o jsonpath='{.status.domain}{\"\\n\"}'"
  echo ""
  echo "Or copy .env.example to .env and edit CLUSTER_APPS_DOMAIN."
  exit 1
fi

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/configure-cluster.sh — do not edit by hand.
global:
  appsDomain: ${CLUSTER_APPS_DOMAIN}
EOF

echo "Wrote ${OUTPUT_FILE}"
echo "  appsDomain: ${CLUSTER_APPS_DOMAIN}"
echo ""
echo "Route hosts that will be created:"
echo "  dev:   https://frida-carclaims-dev.${CLUSTER_APPS_DOMAIN}/"
echo "  stage: https://frida-carclaims-stage.${CLUSTER_APPS_DOMAIN}/"
echo "  prod:  https://frida-carclaims.${CLUSTER_APPS_DOMAIN}/"
