global:
  namespace: frida-car-claims-dev
  partOf: frida-carclaims
  environment: dev
  skipNamespace: true

frontend:
  image:
    repository: quay.io/mklaasse/frida-carclaims-frontend
    tag: latest

backend:
  serviceName: frida-carclaims-dev
  image:
    repository: quay.io/mklaasse/frida-carclaims-backend-ai
    tag: latest
  config:
    chatBaseUrl: "https://api.openai.com/v1/"
    chatModel: "gpt-4o-mini"
    chatTimeout: "120s"
    transcriptionBaseUrl: "https://api.openai.com/v1/"
    transcriptionModel: "whisper-1"
    logLevelClickKlaassen: "INFO"
    logLevelLangchain4j: "INFO"
    httpAccessLogEnabled: "true"

